#!/usr/bin/env node

var fs = require('fs');
var file = process.argv[2];
var calculations = require('./game-functions.js');
var readline = require('readline');

var rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});


var options = { encoding: 'utf8' };
fs.readFile(file, options, function(err, contents) {
  var obj = JSON.parse(contents);
  // console.log('%j', obj.rooms);
  var startRoom;
  var treasureRoom;

  obj.rooms.forEach(function(room) {
    if (room.entrance) {
       startRoom = room;
    }
    if (room.treasure) {
       treasureRoom = room;
    } 
  });

	console.log(startRoom);
	console.log(treasureRoom);

  // User interface--------------------------


  var question = 'You are standing in a room.  There are doors.  Which direction would You' +
    'like to take?  ';
  rl.question(question, function(direction) {
    console.log('direction: %s', direction);

    
    var resultRoom = calculations.nextRoom(startRoom, direction, obj.rooms);
    console.log(resultRoom);

    rl.close();
  });

});
